### ISSUE TITLE
Any document about it?

### ISSUE THREAD

**Issue by Gatsby23** [zhaoqj23/FE-GUT#1]

**Comment by zhaoqj23** [comment]
This work has been submitted to ION GNSS+ 2024. The paper will be uploaded in the future.

**Comment by Gatsby23** [comment]
> This work has been submitted to ION GNSS+ 2024. The paper will be uploaded in the future.

OK, maybe could provide an arxiv version?

**Comment by zhaoqj23** [comment]
I'm sorry, but only the extended abstract is done. If you have any questions, feel free to contact me directly.
