### ISSUE TITLE
confused by EKF

### ISSUE THREAD

**Issue by Redkaido** [zhaoqj23/FE-GUT#2]
Hi, Dr Zhao,
I have some issues to consult with you.
1. Is EKF only for the intial parameters?
2. In line 209, gnss_uwb.cc, why state_curr value is from EKF?
3.  If issue 2 is valid, what the role of FGO? state_curr value may be given following line 151.

Thank you for your answers.

Best regards,
Jun

**Comment by zhaoqj23** [comment]
Thanks for your questions!
In this library, EKF is used not only for the parameter initialization, but also for the position and velocity estimation. FGO is utilized to estimate the time-offset between the GNSS and UWB measurements. You can read the extend abstract attached for more information.
Best regards,
Zhao
[FE_GUT_Extended_Abstract.pdf](https://github.com/zhaoqj23/FE-GUT/files/14814660/FE_GUT_Extended_Abstract.pdf)
